### ISSUE TITLE
how to generalize to alfworld 

### ISSUE THREAD

**Issue by LuoKaiGSW** [allenai/lumos#3]
I am curious about how to organize the prompt when encountering tasks like alfworld. Because several tasks mentioned in the paper do not have a strong dependency on environment feedback, while alfworld requires finding things based on environment feedback. The number of actions needed for the grounding module in alfworld is not fixed. Therefore, I am troubled by how to use the trained model from the paper to evaluate alfworld.

**Comment by WadeYin9712** [comment]
Hi Luokai,

Thank you so much for your interest in Lumos!

Currently, Lumos may not be strong enough to tackle problems with unfixed steps. But at least you can try to follow the WebShop prompt provided in our Lumos paper. We provide some in-context examples to tell the model which subgoals you can plan and which actions you can take. Then the model may be able to simulate the style of your in-context examples, then can be applied to new tasks. 

To add, AlfWorld is actually one of our ongoing expanded training task types. Hopefully in the next 1-2 months, we will have a new Lumos version which can perform AlfWorld and other embodied tasks well. Stay tuned!

**Comment by LuoKaiGSW** [comment]
> Hi Luokai,
> 
> Thank you so much for your interest in Lumos!
> 
> Currently, Lumos may not be strong enough to tackle problems with unfixed steps. But at least you can try to follow the WebShop prompt provided in our Lumos paper. We provide some in-context examples to tell the model which subgoals you can plan and which actions you can take. Then the model may be able to simulate the style of your in-context examples, then can be applied to new tasks.
> 
> To add, AlfWorld is actually one of our ongoing expanded training task types. Hopefully in the next 1-2 months, we will have a new Lumos version which can perform AlfWorld and other embodied tasks well. Stay tuned!

Okay, thank you for your response. Looking forward to your progress.
