### ISSUE TITLE
Understanding environment usage during web navigation

### ISSUE THREAD

**Issue by DanielRoeder1** [allenai/lumos#4]
First, of all great work, and thank you for sharing all of this publically!

I looked through your code to understand how Lumos tackles the Mind2Web task.

From my observations of the intermediate prompts being generated, it appears that Lumos never actually observes the environment (i.e. the HTML or in this case the available actions).

My understanding:
1. Given a task query the planner creates initial subgoals without observing the current webpage (or its actions)
2. The grounding model creates a structured action string (again without observing the webpage)
3. The query model is utilized during execution to select fitting DOM nodes based on the action string 
4. The action is executed based on the query models ranking of DOM nodes

If this is correct then environment observations only appear during the action execution step making the selection of actions/grounding of actions blind to the current environment?

Please correct me if I am wrong :)

**Comment by WadeYin9712** [comment]
Hi Daniel,

Thank you for the insightful question!

For Mind2Web, the execution results are simply the ground-truth subgoals they have done previously. It is for telling the planning modules what they finished and planning module needs to think what they can do next. This might be the simplest form of environment feedbacks.

I believe that feeding the current HTML code will make the planning more grounded and it's completely doable within our framework. The only concern we had is that the HTML tags are too lengthy, and it is much longer than the other involved tasks. To better unify and balance the tasks with the execution feedbacks of various lengths, we choose the simplest one. But it is a very interesting challenge to compress the execution results while maintaining the information that the execution results convey.

**Comment by DanielRoeder1** [comment]
Hi Wade, 

thank you for the quick response!

Just a quick check, is the same true for the WebShop implementation? (i.e. the planning/grounding model does not receive a direct observation of the environment)

I am currently experimenting with grounding LLMs with compressed HTML representations so I am excited to see if Lumos can benefit from it!

**Comment by WadeYin9712** [comment]
Hi Daniel,

Thanks for the nice words!

WebShop actually receives the direct observation, because the observation can be expressed in a short text, compared to Mind2Web.

Yeah I believe Lumos would definitely benefit a lot from grounding to real HTML code when planning. Look forward to your future works!
